/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_doubly_linked_list.ck" instead.
 */

#include <check.h>

#line 1 "test_doubly_linked_list.ck"
#include "doubly_linked_list.h"
#include <stdio.h>
#include <stdlib.h>

List *list;

void list_setup(){
    list = new_doubly_linked_list();
    ck_assert_msg(list != NULL, "list_setup failed...\n");
}

void list_teardown() {
    destroy(list);
}




START_TEST(test_append)
{
#line 22
    list = new_doubly_linked_list();
    ck_assert_msg(append(list, 1) == 0, "test_append failed...\n");
    ck_assert_msg(append(list, 2) == 0, "test_append failed...\n");
    ck_assert_msg(append(list, 3) == 0, "test_append failed...\n");

}
END_TEST

START_TEST(test_print)
{
#line 28
    list = new_doubly_linked_list();
    print(list);
    append(list, 1);
    print(list);
    append(list, 2);
    print(list);
    append(list, 3);
    print(list);

}
END_TEST

START_TEST(test_prepend)
{
#line 38
    list = new_doubly_linked_list();
    ck_assert_msg(prepend(list, 1) == 0, "test_prepend failed...\n");
    ck_assert_msg(prepend(list, 2) == 0, "test_prepend failed...\n");
    ck_assert_msg(prepend(list, 3) == 0, "test_prepend failed...\n");

}
END_TEST

START_TEST(test_insert)
{
#line 44
    list = new_doubly_linked_list();
    ck_assert_msg(insert(list, -1, 1) == -1, "test_insert 1 failed...\n");
    append(list, 1);
    append(list, 2);
    ck_assert_msg(insert(list, 0, 1) == 0, "test_insert 2 failed...\n");
    ck_assert_msg(insert(list, 1, 2) == 0, "test_insert 3 failed...\n");
    ck_assert_msg(insert(list, 4, 1) == -1, "test_insert 4 failed...\n");

}
END_TEST

START_TEST(test_delete_note)
{
#line 53
    list = new_doubly_linked_list();
    ck_assert_msg(delete_note(list, 0) == -1, "test_delete_note 1 failed...\n");
    ck_assert_msg(delete_note(list, -1) == -1, "test_delete_note 2 failed...\n");
    append(list, 1);
    ck_assert_msg(delete_note(list, 1) == -1, "test_delete_note 3 failed...\n");
    append(list, 2);
    append(list, 3);
    ck_assert_msg(delete_note(list, 0) == 0, "test_delete_note 4 failed...\n");
    ck_assert_msg(delete_note(list, 1) == 0, "test_delete_note 5 failed...\n");

}
END_TEST

START_TEST(test_count)
{
#line 64
    list = new_doubly_linked_list();
    append(list, 1);
    append(list, 1);
    append(list, 2);
    ck_assert_msg(count(list, 0) == 0, "test_count 1 failed...\n");
    ck_assert_msg(count(list, 1) == 2, "test_count 2 failed...\n");
    ck_assert_msg(count(list, 2) == 1, "test_count 3 failed...\n");

}
END_TEST

START_TEST(test_get_item)
{
#line 73
    list = new_doubly_linked_list();
    append(list, 1);
    append(list, 2);
    ck_assert_msg(get_item(list, -1) == -1, "test_get_item 1 failed...\n");
    ck_assert_msg(get_item(list, 2) == -1, "test_get_item 2 failed...\n");
    ck_assert_msg(get_item(list, 0) == 1, "test_get_item 3 failed...\n");
    ck_assert_msg(get_item(list, 1) == 2, "test_get_item 3 failed...\n");

}
END_TEST

START_TEST(test_asc_sort)
{
#line 82
    list = new_doubly_linked_list();
    int compare(const int *n1, const int *n2){
        if (*n1 == *n2){
            return 0;
        } else if (*n1 < *n2) {
            return -1;
        } else if (*n1 > *n2) {
            return 1;
        } else {
            return 0;
        }
    }
    for (int i = 0; i < 100; i++) {
        append(list, (int)(rand() % 100));
    }
    int arr[list->length];
    for (int i = 0; i < list->length; i++) {
        arr[i] = get_item(list, i);
    }
    qsort(arr, list->length, sizeof(int), (void *)compare);
    asc_sort(list);
    for (int i = 0; i < list->length; i++) {
        ck_assert_msg(get_item(list, i) == arr[i], "test_asc_sort 1 failed...\n");
    }

}
END_TEST

START_TEST(test_update)
{
#line 108
    list = new_doubly_linked_list();
    ck_assert_msg(update(list, 0, 1) == -1, "test_update 1 failed...\n");
    append(list, 1);
    append(list, 2);
    ck_assert_msg(update(list, -1, 1) == -1, "test_update 2 failed...\n");
    ck_assert_msg(update(list, 0, 2) == 0, "test_update 3 failed...\n");

}
END_TEST

START_TEST(test_clear)
{
#line 116
    list = new_doubly_linked_list();
    ck_assert_msg(clear(list) == 0, "test_clear 1 failed...\n");
    append(list, 1);
    append(list, 2);
    append(list, 3);
    ck_assert_msg(list->length == 3, "test_clear 2 failed...\n");
    ck_assert_msg(clear(list) == 0, "test_clear 3 failed...\n");
    ck_assert_msg(list->length == 0, "test_clear 4 failed...\n");


}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("List");
    TCase *tc1_1 = tcase_create("List Util");
    SRunner *sr = srunner_create(s1);
    int nf;

    /* User-specified pre-run code */
#line 127
    tcase_add_checked_fixture(tc1_1, list_setup, list_teardown);
    srunner_set_log(sr, "list_log.txt");


    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_append);
    tcase_add_test(tc1_1, test_print);
    tcase_add_test(tc1_1, test_prepend);
    tcase_add_test(tc1_1, test_insert);
    tcase_add_test(tc1_1, test_delete_note);
    tcase_add_test(tc1_1, test_count);
    tcase_add_test(tc1_1, test_get_item);
    tcase_add_test(tc1_1, test_asc_sort);
    tcase_add_test(tc1_1, test_update);
    tcase_add_test(tc1_1, test_clear);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    /* User-specified post-run code */
#line 131
    if (nf != 0) {
        printf("%d tests failed.", nf);
    }
    return 0;
}
