/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_linked_list_stack.ck" instead.
 */

#include <check.h>

#line 1 "test_linked_list_stack.ck"
#include "linked_list_stack.h"
#include <stdio.h>
#include <stdlib.h>

Stack *stack;
Node *node;

void stack_setup(){
    stack = init_stack();
    ck_assert_msg(stack != NULL, "stack_setup 1 failed...\n");
    ck_assert_msg(stack->length == 0, "stack_setup 2 failed...\n");
}

void stack_teardown() {
    destroy(stack);
}



START_TEST(test_new_node)
{
#line 23
    node = new_node(1);
    ck_assert_msg(node != NULL, "test_new_node 1 failed...\n");
    ck_assert_msg(node->next == NULL, "test_new_node 2 failed...\n");
    ck_assert_msg(node->val == 1, "test_new_node 3 failed...\n");

}
END_TEST

START_TEST(test_push)
{
#line 29
    stack = init_stack();
    ck_assert_msg(push(stack, 1) == 0, "test_push 1 failed...\n");
    ck_assert_msg(push(stack, 2) == 0, "test_push 2 failed...\n");
    ck_assert_msg(push(stack, 3) == 0, "test_push 3 failed...\n"); 
    ck_assert_msg(stack->length == 3, "test_push 4 failed...\n");

}
END_TEST

START_TEST(test_pop)
{
#line 36
    stack = init_stack();
    ck_assert_msg(pop(stack) == -1, "test_pop 1 failed...\n");
    push(stack, 1);
    push(stack, 2);
    push(stack, 3);
    ck_assert_msg(pop(stack) == 3, "test_pop 2 failed...\n");
    ck_assert_msg(stack->length == 2, "test_pop 3 failed...\n");
    ck_assert_msg(pop(stack) == 2, "test_pop 4 failed...\n");
    ck_assert_msg(stack->length == 1, "test_pop 5 failed...\n");
    ck_assert_msg(pop(stack) == 1, "test_pop 6 failed...\n");
    ck_assert_msg(stack->length == 0, "test_pop 7 failed...\n");

}
END_TEST

START_TEST(test_get_top)
{
#line 49
    stack = init_stack();
    ck_assert_msg(get_top(stack) == -1, "test_get_top 1 failed...\n");
    push(stack, 1);
    ck_assert_msg(get_top(stack) == 1, "test_get_top 1 failed...\n");
    push(stack, 2);
    ck_assert_msg(get_top(stack) == 2, "test_get_top 2 failed...\n");
    push(stack, 3);
    ck_assert_msg(get_top(stack) == 3, "test_get_top 3 failed...\n");

}
END_TEST

START_TEST(test_print)
{
#line 59
    stack = init_stack();
    print(stack);
    push(stack, 1);
    print(stack);
    push(stack, 2);
    print(stack);
    push(stack, 3);
    print(stack);
    push(stack, 4);
    print(stack);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Stack");
    TCase *tc1_1 = tcase_create("Stack Util");
    SRunner *sr = srunner_create(s1);
    int nf;

    /* User-specified pre-run code */
#line 71
    tcase_add_checked_fixture(tc1_1, stack_setup, stack_teardown);
    srunner_set_log(sr, "stack_log.txt");


    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_new_node);
    tcase_add_test(tc1_1, test_push);
    tcase_add_test(tc1_1, test_pop);
    tcase_add_test(tc1_1, test_get_top);
    tcase_add_test(tc1_1, test_print);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    /* User-specified post-run code */
#line 75
    if (nf != 0) {
        printf("%d tests failed.", nf);
    }
    return 0;
}
